# yaml
services:
  - type: web
    name: plateforme-donnees-api
    env: python
    plan: free
    buildCommand: pip install -r plateforme_donnees/requirements.txt && pip install gunicorn || true && cd plateforme_donnees && python manage.py collectstatic --noinput && python manage.py migrate --noinput && python manage.py creer_superuser
    startCommand: cd plateforme_donnees && gunicorn plateforme_donnees.wsgi:application --bind 0.0.0.0:$PORT --workers 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: plateforme_donnees.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: plateforme-db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: "4"
      - key: DJANGO_SUPERUSER_USERNAME
        value: ""
      - key: DJANGO_SUPERUSER_PASSWORD
        value: ""
    autoDeploy: true

  - type: cron
    name: moissonneur
    schedule: "*/15 * * * *"
    env: python
    buildCommand: pip install -r plateforme_donnees/requirements.txt
    startCommand: cd plateforme_donnees && python manage.py moissonner
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: plateforme-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: plateforme_donnees.settings
      - key: PYTHON_VERSION
        value: 3.12.0

databases:
  - name: plateforme-db
    plan: free
